name: Bug Fix Pull Request
description: Submit a fix for a reported bug.
title: "[Bug Fix] <BUG_DESCRIPTION>"
labels: ["bug", "fix"]
assignees: []

body:
  - type: input
    id: bug_description
    attributes:
      label: Bug Description
      description: Provide a short description of the bug you are fixing.
      placeholder: "Fixes division by zero error in safe_divide function."
    validations:
      required: true

  - type: input
    id: issue_reference
    attributes:
      label: Related Issue (if applicable)
      description: Provide the issue number this PR fixes (e.g., `Fixes #42`).
      placeholder: "Fixes #42"
    validations:
      required: false

  - type: textarea
    id: bug_details
    attributes:
      label: Bug Details
      description: Describe the bug, including how it was discovered and its impact on the project.
      placeholder: |
        "Describe the bug in detail, including how to reproduce it and its impact."
    validations:
      required: true

  - type: textarea
    id: fix_implementation
    attributes:
      label: Fix Implementation
      description: Explain how the bug was fixed and why this approach was chosen.
      placeholder: |
        "Describe the changes made to fix the bug, including why this solution was chosen."
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing Information
      description: Describe how you tested the bug fix, including test cases or steps to verify the fix.
      placeholder: |
        "Provide test cases, unit test results, or steps to manually verify that the bug is fixed."